/**
 * 动画资源（APNG，catbox 外链集中维护）
 * 格式限定：本目录仅使用 .html / .css / .js
 * 使用注释按 Slash / Recovery / State / Hit 等分组。
 */
(function () {
  window.ANIMATIONS = {
    // ---------- Slash 组（斩击/挥砍）----------
    Slash: 'https://files.catbox.moe/c0gbkh.png',
    SlashFire: 'https://files.catbox.moe/hbvi0u.png',
    SlashIce: 'https://files.catbox.moe/kogf76.png',
    SlashPhoton: 'https://files.catbox.moe/3bbf4m.png',
    SlashSpecial1: 'https://files.catbox.moe/ll7gpp.png',
    SlashSpecial2: 'https://files.catbox.moe/n2jd29.png',
    SlashSpecial3: 'https://files.catbox.moe/hilznn.png',
    SlashThunder: 'https://files.catbox.moe/aulcf6.png',
    'Slash4': 'https://files.catbox.moe/oljwi2.png',
    'Slash5': 'https://files.catbox.moe/27e561.png',
    'Slash6': 'https://files.catbox.moe/48gr5j.png',

    // ---------- Recovery 组（恢复）----------
    Recovery3: 'https://files.catbox.moe/93lwsw.png',
    Recovery4: 'https://files.catbox.moe/7rec4w.png', // 护盾
    Recovery5: 'https://files.catbox.moe/whjkry.png',
    Recovery1: 'https://files.catbox.moe/p7ncto.png',
    Recovery2: 'https://files.catbox.moe/zs6zme.png',
    Revival1: 'https://files.catbox.moe/bn9b4z.png',
    Revival2: 'https://files.catbox.moe/n7srtm.png',

    // ---------- State 组（状态）----------
    StateSilent: 'https://files.catbox.moe/iv8908.png',
    StateUp1: 'https://files.catbox.moe/2k25uo.png',
    StateUp2: 'https://files.catbox.moe/gnyl2h.png',
    StateDeath: 'https://files.catbox.moe/xbmjeq.png',
    StateDown1: 'https://files.catbox.moe/8y60sw.png',
    StateDown2: 'https://files.catbox.moe/vq2lf2.png',
    StateDown3: 'https://files.catbox.moe/6l1vwo.png',
    StateParalys: 'https://files.catbox.moe/kyadpt.png',
    StatePoison: 'https://files.catbox.moe/8icirp.png',
    StateSleep: 'https://files.catbox.moe/t05nzx.png',
    StateChaos: 'https://files.catbox.moe/1lishy.png',
    StateDark: 'https://files.catbox.moe/e7manc.png',
    'up-1': 'https://files.catbox.moe/gy30k9.png',

    // ---------- Stick 组（棍棒/杖）----------
    Stick: 'https://files.catbox.moe/2oj7p8.png',
    StickPhoton: 'https://files.catbox.moe/tvi6jh.png',
    StickSpecial1: 'https://files.catbox.moe/umrsse.png',
    StickSpecial2: 'https://files.catbox.moe/zb758o.png',
    StickSpecial3: 'https://files.catbox.moe/zz09h4.png',

    // ---------- PreSpecial 组（预备特技）----------
    PreSpecial1: 'https://files.catbox.moe/j234hu.png',
    PreSpecial2: 'https://files.catbox.moe/mn2ves.png',
    PreSpecial3: 'https://files.catbox.moe/7b0n3j.png',

    // ---------- Claw 组（爪击）----------
    Claw: 'https://files.catbox.moe/a8qolj.png',
    ClawSpecial1: 'https://files.catbox.moe/qqp75m.png',
    ClawSpecial2: 'https://files.catbox.moe/p5ew2q.png',

    // ---------- Cure 组（治疗）----------
    Cure2: 'https://files.catbox.moe/g99nvd.png',
    Cure3: 'https://files.catbox.moe/vyba15.png',
    Cure4: 'https://files.catbox.moe/itjw17.png',
    Cure1: 'https://files.catbox.moe/et7yzj.png',
    Cure5: 'https://files.catbox.moe/poy68z.png',
    Cure6: 'https://files.catbox.moe/4cg22n.png',
    'E-cure1': 'https://files.catbox.moe/ua02um.png',

    // ---------- Hit 组（受击/命中）----------
    Hit1: 'https://files.catbox.moe/eufbw3.png',
    Hit2: 'https://files.catbox.moe/uey48b.png',
    HitFire: 'https://files.catbox.moe/66c4bc.png',
    HitIce: 'https://files.catbox.moe/x478q5.png',
    HitPhoton: 'https://files.catbox.moe/c2i2sc.png',
    HitSpecial2: 'https://files.catbox.moe/qgx8uq.png',
    HitSpecial1: 'https://files.catbox.moe/clh62v.png',
    HitThunder: 'https://files.catbox.moe/a0ls1f.png',
    Hit3: 'https://files.catbox.moe/3484nt.png',

    // ---------- Fire 组（火焰）----------
    Fire2: 'https://files.catbox.moe/tyt73c.png',
    Fire3: 'https://files.catbox.moe/aep8yw.png',
    Fire1: 'https://files.catbox.moe/w2w61s.png',
    efecto_fuego: 'https://files.catbox.moe/8omii5.png',
    'E-fire1': 'https://files.catbox.moe/93g0q2.png',
    'E-fire2': 'https://files.catbox.moe/3oxg6r.png',
    'E-fire3': 'https://files.catbox.moe/6qn84h.png',
    'E-fire4': 'https://files.catbox.moe/4r6nae.png',
    'E-fire5': 'https://files.catbox.moe/yul2j1.png',
    'E-fire6': 'https://files.catbox.moe/k1bqm4.png',
    'E-fire7': 'https://files.catbox.moe/fn4i56.png',
    'E-fire8': 'https://files.catbox.moe/hpwc0p.png',
    'E-fire9': 'https://files.catbox.moe/tzbq46.png',
    'E-fire10': 'https://files.catbox.moe/9ffwog.png',
    'E-fire11': 'https://files.catbox.moe/ve5q63.png',
    Fire4: 'https://files.catbox.moe/auavtg.png',
    Fire5: 'https://files.catbox.moe/9v9rse.png',

    // ---------- Ice 组（冰）----------
    Ice1: 'https://files.catbox.moe/p12vk0.png',
    Ice2: 'https://files.catbox.moe/pra0i9.png',
    Ice3: 'https://files.catbox.moe/jiv6tv.png',
    Ice4: 'https://files.catbox.moe/zkaopc.png',
    Ice5: 'https://files.catbox.moe/im9lwr.png',
    Ice6: 'https://files.catbox.moe/umwvgf.png',

    // ---------- Thunder 组（雷）----------
    Thunder2: 'https://files.catbox.moe/whgzo8.png',
    Thunder1: 'https://files.catbox.moe/crdufc.png',
    Thunder3: 'https://files.catbox.moe/fwqka3.png',
    Thunder4: 'https://files.catbox.moe/6vkh3w.png',
    Thunder5: 'https://files.catbox.moe/wfvzep.png',
    'E-thunder1': 'https://files.catbox.moe/jgsmlm.png',
    'E-thunder2': 'https://files.catbox.moe/jp02il.png',
    'E-thunder3': 'https://files.catbox.moe/w58b8t.png',

    // ---------- Holy 组（神圣/圣光）----------
    Holy1: 'https://files.catbox.moe/nfro2e.png',
    Holy2: 'https://files.catbox.moe/5bi13a.png',
    Holy3: 'https://files.catbox.moe/6mvk2n.png',
    Holy4: 'https://files.catbox.moe/vctca0.png',
    Holy5: 'https://files.catbox.moe/35660p.png',
    'E-holy1': 'https://files.catbox.moe/nfro2e.png',
    'E-holy2': 'https://files.catbox.moe/5bi13a.png',
    'E-holy3': 'https://files.catbox.moe/6mvk2n.png',

    // ---------- Water 组（水）----------
    Water5: 'https://files.catbox.moe/pj4w8s.png',
    Water1: 'https://files.catbox.moe/lvyxrk.png',
    Water2: 'https://files.catbox.moe/rjxn17.png',
    Water3: 'https://files.catbox.moe/e3xexx.png',

    // ---------- Wind 组（风）----------
    Wind3: 'https://files.catbox.moe/kc4b9p.png',
    Wind2: 'https://files.catbox.moe/65012u.png',
    Wind4: 'https://files.catbox.moe/mukxvo.png',
    Wind5: 'https://files.catbox.moe/03km6c.png',
    'E-wind1': 'https://files.catbox.moe/wtt6c6.png',
    'E-wind2': 'https://files.catbox.moe/g77yjb.png',
    'E-wind3': 'https://files.catbox.moe/50tj4y.png',

    // ---------- Earth 组（地/土）----------
    Earth3: 'https://files.catbox.moe/o8j88h.png',
    Earth4: 'https://files.catbox.moe/i9y9uh.png',
    Earth5: 'https://files.catbox.moe/rj5mwh.png',
    Earth1: 'https://files.catbox.moe/wz2r1w.png',
    Earth2: 'https://files.catbox.moe/2z40y2.png',

    // ---------- Darkness 组（暗/黑暗）----------
    Darkness1: 'https://files.catbox.moe/hvai7o.png',
    Darkness2: 'https://files.catbox.moe/rm6aen.png',
    Darkness3: 'https://files.catbox.moe/7jklah.png',
    Darkness4: 'https://files.catbox.moe/domuoc.png',
    Darkness5: 'https://files.catbox.moe/rg383u.png',
    Dark1: 'https://files.catbox.moe/ogcmfe.png',
    'E-dark1': 'https://files.catbox.moe/5p18py.png',

    // ---------- Light 组（光）----------
    Light2: 'https://files.catbox.moe/7g1tfv.png',
    Light3: 'https://files.catbox.moe/4fq1y1.png',
    Light4: 'https://files.catbox.moe/kzscjt.png',
    Light1: 'https://files.catbox.moe/2n8dmi.png',
    'E-light1': 'https://files.catbox.moe/3x9120.png',
    'E-light2': 'https://files.catbox.moe/zz6rol.png',
    'r-light1': 'https://files.catbox.moe/58z2jk.png',
    'r-light2': 'https://files.catbox.moe/q5ii6y.png',
    'r-light3': 'https://files.catbox.moe/wln3nt.png',

    // ---------- Mist 组（雾）----------
    Mist: 'https://files.catbox.moe/3ht08z.png',
    'Mist-Pink': 'https://files.catbox.moe/epz1tu.png',

    // ---------- 其他单条（嚎叫/诅咒/激光/魔法/爆炸/闪光/枪/箭/变身/流星/花粉/歌/音速/特技等）----------
    Howl: 'https://files.catbox.moe/n125et.png',
    Curse: 'https://files.catbox.moe/9ozin1.png',
    Laser1: 'https://files.catbox.moe/4n6p0n.png',
    Laser2: 'https://files.catbox.moe/vo7ire.png',
    Magic2: 'https://files.catbox.moe/j0h16m.png',
    Magic1: 'https://files.catbox.moe/t3jxmz.png',
    Explosion1: 'https://files.catbox.moe/4lvtfa.png',
    Explosion2: 'https://files.catbox.moe/kojby7.png',
    Flash: 'https://files.catbox.moe/1jvrjx.png',
    Gun1: 'https://files.catbox.moe/t46iyq.png',
    Gun2: 'https://files.catbox.moe/12b3um.png',
    Gun3: 'https://files.catbox.moe/hlz0hj.png',
    ArrowSpecial: 'https://files.catbox.moe/5d29la.png',
    Monster_Change_Big: 'https://files.catbox.moe/b7ihq8.png',
    Meteor: 'https://files.catbox.moe/y74rfl.png',
    Pollen: 'https://files.catbox.moe/ubqyfu.png',
    Song: 'https://files.catbox.moe/xrtonl.png',
    Sonic: 'https://files.catbox.moe/vx9ex5.png',
    Special1: 'https://files.catbox.moe/zp01kr.png',
    Special2: 'https://files.catbox.moe/c0bjsi.png',
    Special3: 'https://files.catbox.moe/jlypud.png',

    // ---------- E-sword 组（剑系）----------
    'E-sword1': 'https://files.catbox.moe/04s21q.png',
    'E-sword2': 'https://files.catbox.moe/lb64h5.png',
    'E-sword3': 'https://files.catbox.moe/dg28s2.png',
    'E-sword4': 'https://files.catbox.moe/m743dx.png',
    'E-sword5': 'https://files.catbox.moe/37t0j8.png',
    'E-sword6': 'https://files.catbox.moe/x7yy7b.png',
    'E-sword7': 'https://files.catbox.moe/hv5jnq.png',
    'E-sword8': 'https://files.catbox.moe/sehhta.png',
    'E-sword9': 'https://files.catbox.moe/8gxixx.png',
    'E-sword10': 'https://files.catbox.moe/yqzu69.png',

    // ---------- E-spear 组（枪矛系）----------
    'E-spear1': 'https://files.catbox.moe/rq6jt0.png',
    'E-spear2': 'https://files.catbox.moe/hvazo3.png',
    'E-spear3': 'https://files.catbox.moe/jm6d25.png',

    // ---------- E-blow 组（打击/吹飞系）----------
    'E-blow1': 'https://files.catbox.moe/2jvre5.png',
    'E-blow3': 'https://files.catbox.moe/wjmr12.png',
    'E-blow4': 'https://files.catbox.moe/tnj2b5.png',
    'E-blow5': 'https://files.catbox.moe/dm8ue6.png',
    'E-blow6': 'https://files.catbox.moe/xc0r8t.png',
    'E-blow7': 'https://files.catbox.moe/920jio.png',
    'E-blow8': 'https://files.catbox.moe/9q6pp3.png',
    'E-blow9': 'https://files.catbox.moe/ehvj6o.png',
    'E-blow10': 'https://files.catbox.moe/oeg27b.png',

    // ---------- E-claw 组（爪系）----------
    'E-claw1': 'https://files.catbox.moe/wpgipn.png',
    'E-claw2': 'https://files.catbox.moe/6i0yjm.png',
    'E-claw3': 'https://files.catbox.moe/5nmayq.png',

    // ---------- E-gun 组（枪械系）----------
    'E-gun1': 'https://files.catbox.moe/ks28xx.png',
    'E-gun2': 'https://files.catbox.moe/lrfgj1.png',
    'E-gun3': 'https://files.catbox.moe/jbouhe.png',

    // ---------- E-其他（护盾/怪物/先驱/陨石/治疗/羽毛/血等）----------
    'E-guard1': 'https://files.catbox.moe/mziuxa.png',
    'E-monster1': 'https://files.catbox.moe/lrk531.png',
    'E-Herald1': 'https://files.catbox.moe/p35ebv.png',
    'E-PhantasmMeteor': 'https://files.catbox.moe/hylmxs.png',
    'E-PhantasmMeteor2': 'https://files.catbox.moe/5rxfbt.png',
    'E-re1': 'https://files.catbox.moe/2gi4sf.png',
    'E-FeatherBomb': 'https://files.catbox.moe/vbj670.png',
    'E-blood1': 'https://files.catbox.moe/i948yl.png',
    'E-blood2': 'https://files.catbox.moe/orapci.png',

    // ---------- pipo 效果图----------
    'pipo-mapeffect022_192': 'https://files.catbox.moe/53xv4g.png',
    'pipo-btleffect209_192': 'https://files.catbox.moe/8cqakj.png',
    'pipo-btleffect210_192': 'https://files.catbox.moe/c3qt57.png',
    'pipo-btleffect211_192': 'https://files.catbox.moe/79axsm.png',
    'pipo-btleffect212_192': 'https://files.catbox.moe/hcfj7l.png',
    'pipo-btleffect213_192': 'https://files.catbox.moe/axf0h6.png',
    'pipo-btleffect214_192': 'https://files.catbox.moe/ehbabd.png',

    // ---------- 单独分组（咬/黑洞/致盲/吹飞/破盾/施法/劈砍/蚀/以太/星闪/雷电/逻辑炸弹/新星/狂暴/封印/射击/暴风/突刺/病毒/屏障/祝福/吸收等）----------
    ACQ011_Bite: 'https://files.catbox.moe/iohvjj.png',
    Blackhole: 'https://files.catbox.moe/614qvn.png',
    Blind: 'https://files.catbox.moe/if91ke.png',
    Blow1: 'https://files.catbox.moe/5y7ja8.png',
    Blow: 'https://files.catbox.moe/rnqnf3.png',
    Breath: 'https://files.catbox.moe/vljto9.png',
    ClawPhoton: 'https://files.catbox.moe/h8co9w.png',
    AC2Q018_Barrier_Break: 'https://files.catbox.moe/xzghtd.png',
    '-AC2Q017_Barrier': 'https://files.catbox.moe/wgzeik.png',
    Cast1: 'https://files.catbox.moe/5jjqe8.png',
    Cast2: 'https://files.catbox.moe/b8ln9r.png',
    Cast3: 'https://files.catbox.moe/lj3z74.png',
    Cast4: 'https://files.catbox.moe/9f4xsi.png',
    Cast5: 'https://files.catbox.moe/9zilxx.png',
    Cast6: 'https://files.catbox.moe/3ty0bz.png',
    Cleave: 'https://files.catbox.moe/0zh26z.png',
    Eclipse: 'https://files.catbox.moe/ho2315.png',
    Ether: 'https://files.catbox.moe/0fpc7s.png',
    StarFlare: 'https://files.catbox.moe/1waz71.png',
    Lightning1: 'https://files.catbox.moe/8ropja.png',
    Lightning2: 'https://files.catbox.moe/pog5rv.png',
    LogicBomb: 'https://files.catbox.moe/wq140b.png',
    Nova: 'https://files.catbox.moe/zf2qr8.png',
    Rage: 'https://files.catbox.moe/tb1s4t.png',
    Seal: 'https://files.catbox.moe/fxgv6h.png',
    Shot: 'https://files.catbox.moe/3m2wsj.png',
    Tempest: 'https://files.catbox.moe/kj0010.png',
    ACQ003_Thrust1: 'https://files.catbox.moe/ono3xy.png',
    Virus1: 'https://files.catbox.moe/5zoi3t.png',
    Virus2: 'https://files.catbox.moe/tj0dk7.png',
    StarBurst: 'https://files.catbox.moe/0v35k3.png',
    Confuse: 'https://files.catbox.moe/7l6uwz.png',
    Benediction: 'https://files.catbox.moe/ogjym6.png',
    Absorb: 'https://files.catbox.moe/m9qqd4.png',
  };

  /** 各 APNG 总播放时长（毫秒），用于只播放一遍时设置定时 */
  window.ANIMATION_DURATIONS = {
    Slash: 100,
    SlashFire: 280,
    SlashIce: 260,
    SlashPhoton: 80,
    SlashSpecial1: 360,
    SlashSpecial2: 320,
    SlashSpecial3: 560,
    SlashThunder: 280,
    'Slash4': 240,
    'Slash5': 260,
    'Slash6': 160,
    Recovery3: 440,
    Recovery4: 360,
    Recovery5: 600,
    Recovery1: 600,
    Recovery2: 380,
    Revival1: 500,
    Revival2: 600,
    StateSilent: 380,
    StateUp1: 380,
    StateUp2: 480,
    StateDeath: 400,
    StateDown1: 240,
    StateDown2: 500,
    StateDown3: 520,
    StateParalys: 440,
    StatePoison: 300,
    StateSleep: 440,
    StateChaos: 480,
    StateDark: 400,
    'up-1': 480,
    Stick: 140,
    StickPhoton: 180,
    StickSpecial1: 200,
    StickSpecial2: 180,
    StickSpecial3: 220,
    PreSpecial1: 540,
    PreSpecial2: 540,
    PreSpecial3: 540,
    Claw: 120,
    ClawSpecial1: 460,
    ClawSpecial2: 240,
    Cure2: 520,
    Cure3: 600,
    Cure4: 260,
    Cure1: 580,
    Cure5: 1160,
    Cure6: 580,
    'E-cure1': 240,
    Hit1: 80,
    Hit2: 60,
    HitFire: 160,
    HitIce: 200,
    HitPhoton: 100,
    HitSpecial2: 140,
    HitSpecial1: 180,
    HitThunder: 140,
    Hit3: 200,
    Fire2: 200,
    Fire3: 520,
    Fire1: 600,
    efecto_fuego: 1000,
    'E-fire1': 480,
    'E-fire2': 320,
    'E-fire3': 320,
    'E-fire4': 320,
    'E-fire5': 300,
    'E-fire6': 360,
    'E-fire7': 240,
    'E-fire8': 400,
    'E-fire9': 380,
    'E-fire10': 800,
    'E-fire11': 680,
    Fire4: 1980,
    Fire5: 980,
    Ice1: 300,
    Ice2: 420,
    Ice3: 180,
    Ice4: 80,
    Ice6: 1000,
    Ice5: 480,
    Thunder2: 120,
    Thunder1: 300,
    Thunder3: 100,
    Thunder4: 240,
    Thunder5: 420,
    'E-thunder1': 220,
    'E-thunder2': 1380,
    'E-thunder3': 300,
    Holy1: 540,
    Holy2: 600,
    Holy3: 300,
    Holy4: 500,
    Holy5: 540,
    'E-holy1': 540,
    'E-holy2': 600,
    'E-holy3': 300,
    Water5: 380,
    Water1: 460,
    Water2: 540,
    Water3: 300,
    Wind3: 280,
    Wind2: 300,
    Wind4: 200,
    Wind5: 560,
    'E-wind1': 380,
    'E-wind2': 620,
    'E-wind3': 360,
    Earth3: 140,
    Earth4: 160,
    Earth5: 600,
    Earth1: 500,
    Earth2: 360,
    Darkness1: 400,
    Darkness2: 420,
    Darkness3: 180,
    Darkness5: 500,
    Dark1: 1000,
    Darkness4: 520,
    'E-dark1': 300,
    Light2: 600,
    Light3: 600,
    Light4: 600,
    Light1: 600,
    'E-light1': 500,
    'E-light2': 580,
    'r-light1': 140,
    'r-light2': 160,
    'r-light3': 160,
    Mist: 100,
    'Mist-Pink': 100,
    Howl: 200,
    Curse: 320,
    Laser1: 420,
    Laser2: 420,
    Magic2: 380,
    Magic1: 280,
    Explosion1: 240,
    Explosion2: 600,
    Flash: 300,
    Gun1: 420,
    Gun2: 500,
    Gun3: 340,
    ArrowSpecial: 220,
    Monster_Change_Big: 840,
    Meteor: 440,
    Pollen: 280,
    Song: 220,
    Sonic: 120,
    Special1: 120,
    Special2: 580,
    Special3: 380,
    'E-sword1': 480,
    'E-sword2': 420,
    'E-sword3': 240,
    'E-sword4': 640,
    'E-sword5': 400,
    'E-sword6': 160,
    'E-sword7': 240,
    'E-sword8': 320,
    'E-sword9': 280,
    'E-sword10': 380,
    'E-spear1': 260,
    'E-spear2': 320,
    'E-spear3': 440,
    'E-blow1': 180,
    'E-blow3': 280,
    'E-blow4': 200,
    'E-blow5': 340,
    'E-blow6': 600,
    'E-blow7': 240,
    'E-blow8': 180,
    'E-blow9': 220,
    'E-blow10': 240,
    'E-claw1': 280,
    'E-claw2': 280,
    'E-claw3': 320,
    'E-gun1': 340,
    'E-gun2': 480,
    'E-gun3': 520,
    'E-guard1': 440,
    'E-monster1': 340,
    'E-Herald1': 360,
    'E-PhantasmMeteor': 860,
    'E-PhantasmMeteor2': 580,
    'E-re1': 520,
    'E-FeatherBomb': 440,
    'E-blood1': 940,
    'E-blood2': 320,
    'pipo-mapeffect022_192': 400,
    'pipo-btleffect209_192': 300,
    'pipo-btleffect210_192': 300,
    'pipo-btleffect211_192': 300,
    'pipo-btleffect212_192': 300,
    'pipo-btleffect213_192': 300,
    'pipo-btleffect214_192': 300,
    ACQ011_Bite: 580,
    Blackhole: 980,
    Blind: 840,
    Blow1: 560,
    Blow: 120,
    Breath: 300,
    ClawPhoton: 160,
    AC2Q018_Barrier_Break: 900,
    '-AC2Q017_Barrier': 860,
    Cast1: 1120,
    Cast2: 1120,
    Cast3: 280,
    Cast4: 560,
    Cast5: 300,
    Cast6: 600,
    Cleave: 280,
    Eclipse: 1000,
    Ether: 900,
    StarFlare: 960,
    Lightning1: 1000,
    Lightning2: 120,
    LogicBomb: 1000,
    Nova: 2000,
    Rage: 600,
    Seal: 600,
    Shot: 280,
    Tempest: 1800,
    ACQ003_Thrust1: 280,
    Virus1: 1180,
    Virus2: 580,
    StarBurst: 740,
    Confuse: 500,
    Benediction: 1000,
    Absorb: 500,
  };
})();
